language: python
python:
  - "3.6"

branches:
  only:
    - master

install:
  - pip install -r requirements.txt
  - pip install -r requirements.dev.txt

script:
  - invoke test --no-functional
  - coverage run --source=oil -m unittest discover -s tests
  - coverage report
